### ISSUE TITLE
Evitar que las imágenes se deformen

### ISSUE THREAD

**Issue by avdata99** [avdata99/codrops-podcast-parlarispa#15]
Hacer que la imagen entre en la pantalla sin deformarse.
Se puede hacer asegurándose que la imagen se achique hasta no sobrepasar el ancho y alto o cortando un poco y tomar un parte de la imagen. Ver que queda mejor 
![image](https://user-images.githubusercontent.com/3237309/68813067-6b45a500-0653-11ea-9a3e-28dc9837c581.png)

**Comment by avdata99** [comment]
Acepté el PR pero se sigue viendo mal
Se que no se pueden hacer milagros pero dejo de leerse el texto
![Selection_2482](https://user-images.githubusercontent.com/3237309/68906142-19b81b80-0722-11ea-949a-8cac0c0311b0.png)
![Selection_2481](https://user-images.githubusercontent.com/3237309/68906143-19b81b80-0722-11ea-9664-7f1163ee2271.png)

**Comment by daniellauro** [comment]
Cómo lo ves ahora @avdata99 ? Yo ya lo veo bien a esto, tanto en mi teléfono cómo en la PC en modo mobile.
