### ISSUE TITLE
Permitir slide de las imagenes

### ISSUE THREAD

**Issue by avdata99** [avdata99/codrops-podcast-parlarispa#16]
Ahora solo se puede pasar con los botones laterales, en el celu debería poder arrastrarse hacia los costados

**Comment by daniellauro** [comment]
Esto está resuelto en c789485aa9d7b4bdc09cca98e16500cf65dd08d7. Acabo de probarlo con mi teléfono por las dudas y está funcionando bien. 

Avisame cualquier cosa.
