### ISSUE TITLE
Cambio en el reproductor

### ISSUE THREAD

**Issue by avdata99** [avdata99/codrops-podcast-parlarispa#17]
El reproductor siempre esta con el MP3 del último episodio.
Definir una forma que sea intuitiva de cambiar. 
Cuando me deslizo entre los episodios o cuando elijo un episodio de la lista se debe poder cambiar el audio

**Comment by daniellauro** [comment]
Antes estaba hecho de forma tal que cuando clickeabas sobre un episodio, el mismo se ponía para reproducir. En su lugar añadí un botón de "Play" al hacer click sobre un episodio porque si estás escuchando un podcast mientras navegás por el sitio y te llama la atención otro episodio, querés leer la descripción completa, clickeaste sobre el episodio y chau podcast que estabas escuchando.

Como para mantener el principio de "navegar sin que se corte el audio". Aún así si querés lo pongo como estaba antes que es como querés en este ticket, avisame @avdata99

**Comment by avdata99** [comment]
Podrías poner un boton chiquito pero notorio de _play_ sobre la imagen de cada episodio donde te parezca que queda mejor (quizás arriba a la derecha) y si se le da click pasa abajo y comienza la reproducción. Si hay otro audio corriendo, lo pisa.
De esta forma navegar por los episodios no interrumpe el audio y el usuario puede interrumpirlo con una acción directa
