### ISSUE TITLE
No refrescar nunca la página

### ISSUE THREAD

**Issue by avdata99** [avdata99/codrops-podcast-parlarispa#2]
El sitio no se debe refrescar completamente al hacer click y moverse entre secciones.
Se puede seguir con la base del template actual o cambiarse por otro.
La home debe eliminarse y que esta sea por defecto el último episodio. De esta forma quizás se simplifica un poco el desarrollo.

Tienen que haber un reproductor web de audio anclado en la parte inferior del sitio y nunca perderse lo que está reproduciendo. Para esto los cambios vía JS deben pasar sin refrescar la página. 
Las URLs deben actualizarse con cada cambio y deben poder usarse para compartir contenido. 
Por ejemplo las URLs pueden ser
 - #episodio-juan-perez
 - #episodio-carlos-gomez
Mejorar las URLs, si tenes los episodios en la base interna podes dejar de usar los UIDs que son feos.
Se puede ver el [JS de los episodios](https://github.com/avdata99/codrops-podcast-parlarispa/blob/master/assets/js/parlarispa-episodio.js) como ayuda para saber como funciona.

Quizas sea mejor sea leer el [JS de la home](https://github.com/avdata99/codrops-podcast-parlarispa/blob/master/assets/js/parlarispa-podcast.js) y guardar todos los episodios en memoria interna para n hacer tantas llamadas API. El cache debería durar 24 hs.
Si puede ser configurable el tiempo del caché, mejor

**Comment by daniellauro** [comment]
Finalizado en commit cd8a6f36ca0d250299bbcad7b8c965a63161b967
