### ISSUE TITLE
Links a plataformas

### ISSUE THREAD

**Issue by avdata99** [avdata99/codrops-podcast-parlarispa#4]
Definir una forma de mostrar los links a otras plataformas de podcasts
Ya está en [el API](https://parlarispa.com/api/v1/podcasts/podcast/aa2b715c-73aa-412a-9e04-100f60881ffa/) pero no en la web todavía.

![image](https://user-images.githubusercontent.com/3237309/66093092-2f53f600-e565-11e9-8377-7ded852b5489.png)

**Comment by daniellauro** [comment]
@avdata99 Podríamos poner un par de botones con imágenes en la barra de navegación superior a modo de links?

**Comment by avdata99** [comment]
Puede ser parte del menu general del que hablamos ayer. 
"Creo que la barra superior puede ser. Un menu que despliegue estas opciones quizás. Elegilo vos y vemos
Quizas debas tener un solo boton de menu, se despliega y entre esas opciones una puede ser suscribite y ahi que despliegues las apps que permiten suscripcion
Me refiero al caso donde este no sea el único menu. Mientras menos botones en la home, mejor
Si puede ser un menu que despliegue las otras opciones, mejor"

Fijate vos que es mejor, un menu grande desde donde salen todos los menues (entre ellos el de suscribirse) o este boton suscribirse con el desplegable de opciones directo en la pantalla. Elegilo segun como veas como estas de espacio
