### ISSUE TITLE
Arrastrar para pasar episodios

### ISSUE THREAD

**Issue by avdata99** [avdata99/codrops-podcast-parlarispa#5]
Permitir navegar entre los episodios (sin que se corte el audio) simplemente arrastrando para derecha e izquierda (anterior/siguiente).
Agregar unos botones a los costados también.

**Comment by daniellauro** [comment]
Esto lo aplico sobre la home? Porque ya hay una sección con el listado de todos los episodios. (_Lo único que me queda sobre eso es hacer que los episodios no se reproduzcan inmediatamente al clickear sobre un episodio y poner en su lugar algún botón de play / abrir_).

Sobre la home podría mostrar un listado de los últimos 5 episodios y hacer un slide con los mismos, pero me parece "redundante". Qué se te ocurre @avdata99 que sería lo mejor?

**Comment by avdata99** [comment]
Eso **es** la home. Al entrar a la web se ve el último episodio directamente y se puede empezar a deslizarse a los costados. 
Podría haber una vista a la que se accede con algún botón. Esta sería una especie de vista en modo _lista_ para mirar más rápido. Podría haber un boton para switchear las vistas.
Pero esto no es importante ya. Si la tenes hecha, la usamos. Si no solo vamos directo a esto.
