### ISSUE TITLE
Templatizar

### ISSUE THREAD

**Issue by avdata99** [avdata99/codrops-podcast-parlarispa#7]
Permitir definir colores base configurables para que haya diferentes _sabores_ de este mismo template

**Comment by daniellauro** [comment]
Andrés, con esto te referís a crear ciertas variables en SCSS que modifiquen colores de la web a gusto del programador? (es decir, el programador tiene que cambiar las variables directamente en el .scss) O que haya una configuración que permita cambiar los colores como tiene el modo nocturno de qhapax por ejemplo?

**Comment by avdata99** [comment]
No es un ticket muy importante.
Si vos quisieras usar este código para reutulizar en otros podcast de la misma plataforma estaría bueno que sea fácil de cambiar si tener que hacer demasiado y si es posible en un archivo de configuración que no quede como parte del repo.
Vos podías definir un archivo de conficuracion y cada cliente lo copia y lo sobreescribe  a su gusto.
Podría cambiar mas cosas además de los colores.
Me gustaría que fuera configurable
De esta forma podría haber una comunidad trabajando en este repo y no se irían por líneas separadas
Si es facil y se puede, sino quedará para despues. Dale a otro ticket.
Este no es importante
